version: 2.1
jobs:
  build:
    docker:
    - image: cimg/python:3.11
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: python -m pip install --upgrade pip
        command: python -m pip install --upgrade pip
    - run:
        name: pip install -r requirements.txt
        command: pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: pytest
        command: pytest
workflows:
  version: 2
  build-test:
    jobs:
    - build
